#!/bin/bash
echo "Checking instructions for spelling errors..."
spell -n instructions.zil | grep -v -Ev "DESC|LIGHTBIT|CRLF|HLIGHT|FCLEAR|COND|LTABLE|PRECHOICE|RTRUE|RFALSE|READLINE|LEXBUF|GETB|TAKEBIT|DATAFILES" | grep -i -v -Ev ": honi|: soit|: qui|: mal|: pense" | uniq
echo
echo "Checking player for spelling errors..."
spell -n player.zil | grep -v -Ev "DESC|COND|LTABLE|RTRUE|RFALSE|PERSONBIT|CRLF|NARTICLEBIT|AUX" | grep -i -v -Ev "longbow|: III's" | uniq
echo
echo "Checking story for spelling errors..."
spell -n story.zil | grep -v -Ev "DESC|LIGHTBIT|CRLF|HLIGHT|FCLEAR|COND|LTABLE|PRECHOICE|RTRUE|RFALSE|READLINE|LEXBUF|GETB|TAKEBIT|DATAFILES" | grep -i -v -Ev "bizan|: oof|cuthbert|philippa|quarterstaves|: ye're|: yerself|: honi|: soit|: qui|: mal|: pense|: ye'd|: yer" | uniq
