#!/bin/bash
echo "Checking instructions for spelling errors..."
spell -n instructions.zil | grep -v -Ev "DESC|LIGHTBIT|CRLF|HLIGHT|FCLEAR|COND|LTABLE|PRECHOICE|RTRUE|RFALSE|READLINE|LEXBUF|GETB|TAKEBIT|DATAFILES" | grep -i -v -Ev ": honi|: soit|: qui|: mal|: pense|gasperini|hescox|busker|arquebusier" | uniq
echo
echo "Checking player for spelling errors..."
spell -n player.zil | grep -v -Ev "DESC|COND|LTABLE|RTRUE|RFALSE|PERSONBIT|CRLF|NARTICLEBIT|AUX" | grep -i -v -Ev "longbow|: III's" | uniq
echo
echo "Checking story for spelling errors..."
spell -n story.zil | grep -v -Ev "DESC|LIGHTBIT|CRLF|HLIGHT|FCLEAR|COND|LTABLE|PRECHOICE|RTRUE|RFALSE|READLINE|LEXBUF|GETB|TAKEBIT|DATAFILES|TWING|CRAA|ACK|AARGH" | grep -i -v -Ev "bizan|: oof|cuthbert|philippa|quarterstaves|ploughing|longbow|quarterstaff|chandos|torchlit|rosalinde|christmastime|manny|artorius|geraint|catraeth|hennebonne|jannedik|crossbowmen|crossbowman|bretons|cannoneers|eyepatch|pamplona|theobald|montjoie|: ye're|: yerself|: honi|: soit|: qui|: mal|: pense|: ye'd|: yer|: plough|: gardyloo|: awroo|: hic|: de|: hoo|: haie|: hyaaagh|: bloops" | uniq
